name: Release Build

on:
  release:
    types: [created]
permissions:
  contents: write
jobs:
  build:
    uses: ./.github/workflows/main.yml

  upload-release-assets:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Linux build
        uses: actions/download-artifact@v4
        with:
          name: linuxBuild
          path: linuxBuild

      - name: Download Windows build
        uses: actions/download-artifact@v4
        with:
          name: windowsBuild
          path: windowsBuild

      - name: Download Mac build
        uses: actions/download-artifact@v4
        with:
          name: macBuild
          path: macBuild

      - name: Create zip archives
        run: |
         cd linuxBuild/linuxBuild && zip -r ../linuxBuild.zip . && cd ..
         cd windowsBuild/windowsBuild && zip -r ../windowsBuild.zip . && cd ..
         cd macBuild/macBuild && zip -r ../macBuild.zip . && cd ..

      - name: Upload all artifacts to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            linuxBuild.zip
            windowsBuild.zip
            macBuild.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
